name: Build Libtorrent
# 手动触发
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 检出libtorrent仓库
    - name: Checkout libtorrent
      uses: actions/checkout@v3
      with:
        repository: 'ArvidN/libtorrent'
        # 包括子模块
        submodules: 'recursive'
    # 安装相关依赖，代码来自官方readme
    - name: Install depends
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-tools-dev libboost-dev libboost-system-dev
        mkdir target
    - name: Build libtorrent
      run: |
        # 使用boost编译，代码来自官方readme，编译日志写入文件
        echo "using gcc ;" >>~/user-config.jam
        b2 crypto=openssl cxxstd=14 release &> target/log.txt
        b2 install --prefix=target
    # 上传target文件夹（包括编译日志和编译好的库文件）
    - name: Upload target
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: target

        

