name: Build Libtorrent
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      run: |
        git clone --recurse-submodules https://github.com/arvidn/libtorrent.git
    - name: Install depends
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-tools-dev libboost-dev libboost-system-dev
