name: Upload artifact

on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Generate demo.txt
      run: echo "Hello, World!" > demo.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: demo.txt
        path: demo.txt
        if-no-files-found: error
